#  一、数组(ndarray)的创建

In [1]:
# 导入numpy库
import numpy as np

In [2]:
# 查看numpy库的所有属性和函数
dir(np)
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

## 1、一维数组的创建

### np.array

In [3]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

### np.arange 函数

In [4]:
b=np.arange(0,10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### np.linspace 

In [5]:
c=np.linspace(0,10,100)
c.shape

(100,)

In [6]:
d=np.linspace(10,100,1000,endpoint=True)
# endploint=True 表示包含结尾的数值1000含在范围内
d[-1:] 

array([100.])

## 2.二维数组的创建

In [7]:
e=np.array([[1,2],[3,4]])
e.shape

(2, 2)

In [8]:
f=np.array([[1,2,3],['3',4,'5']],dtype='float')
f
# 此时的各元素都被强制转化成字符串类型

array([[1., 2., 3.],
       [3., 4., 5.]])

In [9]:
# g=np.array([[1,2,3],['a','b','c']],dtype='float')
# 存在'a'等不适float类型
# 此时的类型应为 object

In [10]:
h=np.array([[1,2,3],['a','b','c']],dtype='object')
h

array([[1, 2, 3],
       ['a', 'b', 'c']], dtype=object)

In [11]:
# 查看数组类型
h.dtype #'O' object

dtype('O')

In [12]:
# 查看numpy的所有数据类型
np.typeDict
# print(np.typeDict)

{'?': numpy.bool_,
 0: numpy.bool_,
 'byte': numpy.int8,
 'b': numpy.int8,
 1: numpy.int8,
 'ubyte': numpy.uint8,
 'B': numpy.uint8,
 2: numpy.uint8,
 'short': numpy.int16,
 'h': numpy.int16,
 3: numpy.int16,
 'ushort': numpy.uint16,
 'H': numpy.uint16,
 4: numpy.uint16,
 'i': numpy.int32,
 5: numpy.int32,
 'uint': numpy.uint32,
 'I': numpy.uint32,
 6: numpy.uint32,
 'intp': numpy.int64,
 'p': numpy.int64,
 9: numpy.int64,
 'uintp': numpy.uint64,
 'P': numpy.uint64,
 10: numpy.uint64,
 'long': numpy.int32,
 'l': numpy.int32,
 7: numpy.int32,
 'L': numpy.uint32,
 8: numpy.uint32,
 'longlong': numpy.int64,
 'q': numpy.int64,
 'ulonglong': numpy.uint64,
 'Q': numpy.uint64,
 'half': numpy.float16,
 'e': numpy.float16,
 23: numpy.float16,
 'f': numpy.float32,
 11: numpy.float32,
 'double': numpy.float64,
 'd': numpy.float64,
 12: numpy.float64,
 'longdouble': numpy.float64,
 'g': numpy.float64,
 13: numpy.float64,
 'cfloat': numpy.complex128,
 'F': numpy.complex64,
 14: numpy.complex64,
 'c

## 3.数组的属性
 - ndim  维数
 - shape  形状
 - size   大小
 - itemsize 每个元素所占用的字节
 - dtype  数据的类型

In [13]:
f.ndim

2

In [14]:
f.shape

(2, 3)

In [15]:
f.size

6

In [16]:
f.itemsize
#每一个元素所占用的字节

8

In [17]:
f.dtype

dtype('float64')

## 4.缺失值问题  单独详细了解

- None 
- np.nan
- np.isnan 函数

In [18]:
type(np.nan)

float

In [19]:
#np.isnan("nan") 这句命令有错误的

In [20]:
type(None)

NoneType

In [21]:
# np.isnan函数的应用
i=np.array([1,2,3,np.nan])
np.isnan(i)

array([False, False, False,  True])

## 5.一些特殊数组的快速创建

- 元素全为0的数组 np.zeros()
- 元素全为1的数组  np.ones()
- 指定元素填充数组  np.full(shape,fill_value)
- 单位矩阵 np.eye()
- 未初始化的指定形状的数组  np.empty(shape)
- 对角矩阵  np.diag([对角线上的数值])

In [22]:
# 元素全为0的数组
np.zeros((2,3))
# 以元组的形式作为数组的形状

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# 元素全为1的数组
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
# 指定元素填充数组
np.full((3,3),"*")

array([['*', '*', '*'],
       ['*', '*', '*'],
       ['*', '*', '*']], dtype='<U1')

In [25]:
np.full((7,6),np.array([1,2,3,4,5,6]))

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

## ***查看函数的用法***

In [26]:
# help
help(np.full)
# ?
np.full?
# np.info()
np.info(np.full)  #查看np.full函数的所有信息

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C')
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, `None`, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of `fill_value` with the given shape, dtype, and order.
    
    See Also
    --------
    full_like : Return a new array with shape of input filled with value.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    zeros : Return a new array setting values 

Signature: np.full(shape, fill_value, dtype=None, order='C')
Docstring:
Return a new array of given shape and type, filled with `fill_value`.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
fill_value : scalar
    Fill value.
dtype : data-type, optional
    The desired data-type for the array  The default, `None`, means
     `np.array(fill_value).dtype`.
order : {'C', 'F'}, optional
    Whether to store multidimensional data in C- or Fortran-contiguous
    (row- or column-wise) order in memory.

Returns
-------
out : ndarray
    Array of `fill_value` with the given shape, dtype, and order.

See Also
--------
full_like : Return a new array with shape of input filled with value.
empty : Return a new uninitialized array.
ones : Return a new array setting values to one.
zeros : Return a new array setting values to zero.

Examples
--------
>>> np.full((2, 2), np.inf)
array([[ inf,  inf],
       [ inf,  inf]])
>>> np.full((2, 2), 

- ### ***单位矩阵***

In [27]:
np.eye(8)  #8*8的方阵

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [28]:
# 未初始化指定形状的数组
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
help(np.empty)

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of uninitialized (arbitrary) data of the given shape, dtype, and
        order.  Object arrays will be initialized to None.
    
    See Also
    --------
    empty_like : Return an empty array with shape and type of input.
    ones : Return a new array setting values to one.
    zeros : Return a new array 

In [30]:
np.empty((3,4))

array([[9.8e-322, 0.0e+000, 0.0e+000, 0.0e+000],
       [0.0e+000, 0.0e+000, 0.0e+000, 0.0e+000],
       [0.0e+000, 0.0e+000, 0.0e+000, 0.0e+000]])

- 对角矩阵 diag

In [31]:
np.diag([1,2,3,4,5,6,7,8,9])

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [32]:
help(np.diag)

Help on function diag in module numpy:

diag(v, k=0)
    Extract a diagonal or construct a diagonal array.
    
    See the more detailed documentation for ``numpy.diagonal`` if you use this
    function to extract a diagonal and wish to write to the resulting array;
    whether it returns a copy or a view depends on what version of numpy you
    are using.
    
    Parameters
    ----------
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.
    
    Returns
    -------
    out : ndarray
        The extracted diagonal or constructed diagonal array.
    
    See Also
    --------
    diagonal : Return specified diagonals.
    diagflat : Create a 2-D array with the flattened input 

## 6.np.random 模块

In [33]:
# 打印出np.random的所有属性的函数
print(dir(np.random))

['Lock', 'RandomState', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'absolute_import', 'beta', 'binomial', 'bytes', 'chisquare', 'choice', 'dirichlet', 'division', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'np', 'operator', 'pareto', 'permutation', 'poisson', 'power', 'print_function', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'warnings', 'weibull', 'zipf']


- 生成随机种子 seed
- 均匀分布
    - rand  生成的随机数值在（0,1）均匀分布范围内
    - uniform 生成的随机数值在指定范围内的 如（x，y）范围内生成
- 根据给定的范围抽取随机整数  randint
- 正态分布
    - randn (0,1) 均值为0，方差为1 从标准正态分布内抽取随机数
    - normal （x,y）在均值为x，方差为y的正态分布内抽取随机数
- 随机选择  np.random.choice(n,p)  n 样本量 p 每个样本被抽中的概率
- 打乱数组元素的排列顺序  np.random.shuffle() 重洗

###  ***seed***

In [34]:
np.random.seed(0)
# 想固定生成的随机数时首先设定一样的随机种子

In [35]:
np.random.rand(10)
# 不设定随机种子时，每运行一次数值都会发生变化

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [36]:
np.random.seed(0)
np.random.rand(10)
# 当随机种子设定后，生成的随机数也就固定下来了。

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

### ***rand***

In [37]:
np.random.rand(25)
# 随机数值的大小在0-1之间

array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443,
       0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194,
       0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ])

In [38]:
np.random.random((5,5)) #起到了与np.random.rand()一样的功效

array([[0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ],
       [0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 0.66676672],
       [0.67063787, 0.21038256, 0.1289263 , 0.31542835, 0.36371077],
       [0.57019677, 0.43860151, 0.98837384, 0.10204481, 0.20887676],
       [0.16130952, 0.65310833, 0.2532916 , 0.46631077, 0.24442559]])

### ***uniform***

In [39]:
np.random.uniform(1,2,(5,5))
#设定取值的范围及形状

array([[1.15896958, 1.11037514, 1.65632959, 1.13818295, 1.19658236],
       [1.36872517, 1.82099323, 1.09710128, 1.83794491, 1.09609841],
       [1.97645947, 1.4686512 , 1.97676109, 1.60484552, 1.73926358],
       [1.03918779, 1.28280696, 1.12019656, 1.2961402 , 1.11872772],
       [1.31798318, 1.41426299, 1.0641475 , 1.69247212, 1.56660145]])

### ***randint***

In [40]:
np.random.randint(10,100,(5,5))

array([[91, 60, 37, 24, 51],
       [68, 75, 46, 20, 96],
       [53, 21, 12, 61, 90],
       [42, 64, 10, 48, 29],
       [56, 52, 66, 70, 87]])

### ***randn*** ***标准正态分布中抽取随机数***

In [41]:
np.random.randn(5,5)

array([[ 9.25250752e-01, -9.04786158e-01,  1.84369153e+00,
         1.52550724e+00, -1.44553558e+00],
       [ 3.77160611e-01, -7.05572292e-02,  6.04159707e-01,
         4.72148998e-01,  8.19917293e-01],
       [ 9.07519617e-01, -5.85822875e-01,  9.37558842e-01,
        -2.54608092e-01,  9.73598712e-01],
       [ 2.07282772e-01,  1.09964197e+00,  9.39896981e-01,
         6.06389001e-01,  1.76084071e-03],
       [-9.90160143e-01,  1.87239408e+00, -2.41073590e-01,
         5.33449070e-02,  1.03081595e+00]])

### ***normal  正态分布***

In [42]:
np.random.normal(2,4,(5,5))

array([[-3.10795595,  5.35087906, -3.96044565, -2.28086001,  1.16348553],
       [ 4.41828911, -4.97223292,  8.09690725,  9.45430127,  7.16551168],
       [ 7.20278509,  5.67281131,  1.36479811, -1.85625344, -5.96311528],
       [ 2.35892291,  2.45941552, -0.34326073,  3.19508815,  2.88903961],
       [ 3.74073187,  1.8170076 ,  2.19959366, -1.74212182,  3.14955061]])

###  ***np.random.choice***

In [43]:
help(np.random.choice)

Help on built-in function choice:

choice(...) method of mtrand.RandomState instance
    choice(a, size=None, replace=True, p=None)
    
    Generates a random sample from a given 1-D array
    
            .. versionadded:: 1.7.0
    
    Parameters
    -----------
    a : 1-D array-like or int
        If an ndarray, a random sample is generated from its elements.
        If an int, the random sample is generated as if a were np.arange(a)
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    replace : boolean, optional
        Whether the sample is with or without replacement
    p : 1-D array-like, optional
        The probabilities associated with each entry in a.
        If not given the sample assumes a uniform distribution over all
        entries in a.
    
    Returns
    --------
    samples : single item o

In [44]:
b=[]
a='abcdefg'
b.extend(a)
np.random.choice(b)

'd'

In [45]:
a='abcde'
b=[]
b.extend(a)
b

['a', 'b', 'c', 'd', 'e']

## 7.累计求和

- np.cumsum()

In [46]:
m=np.random.randint(10,100,(3,3))
print('m=',m)
print('m.cumsum()=',m.cumsum())

m= [[56 30 63]
 [39 77 45]
 [49 19 83]]
m.cumsum()= [ 56  86 149 188 265 310 359 378 461]


In [47]:
n=np.random.randint(10,100,(3,3))
print('n=',n)
# 将其压成一行
print('n.ravel()=',n.ravel())
# 将其压成一行进行累加
print('n.cumsum()=',n.cumsum())
# axis=0 按列累加
print('n.cumsum(axis=0)=',n.cumsum(axis=0))
# axis=1 按行累加
print('n.cumsum(axis=1)=',n.cumsum(axis=1))

n= [[51 33 13]
 [56 60 13]
 [41 19 20]]
n.ravel()= [51 33 13 56 60 13 41 19 20]
n.cumsum()= [ 51  84  97 153 213 226 267 286 306]
n.cumsum(axis=0)= [[ 51  33  13]
 [107  93  26]
 [148 112  46]]
n.cumsum(axis=1)= [[ 51  84  97]
 [ 56 116 129]
 [ 41  60  80]]


# 二、数组的排序

- np.argsort()  默认按行进行排序
- sorted() 与lambda连用
- np.sort()  默认每行内进行一个排序 升序  

- ### ***一维数组***

In [48]:
# 设定一个随机种子防止每次运行数值都会变动，
# 不利于后续的使用
np.random.seed(1)
# 此次在标准正态分布中抽取随机数
r=np.random.randn(9)

# 打印出r
print(r)
# 打印出升序排序后按原始位置的索引作为返回值的np.argsort()
print('r.argsort():',r.argsort()) #数值按从小到大

# 从大到小的排序返回原始位置的索引
print('np.argsort(-r)',np.argsort(-r))
print('升序排序')
print('np.sort(r):',np.sort(r))
print('降序排序') 
print('np.sort(-r):',np.sort(-r))

[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763 -2.3015387
  1.74481176 -0.7612069   0.3190391 ]
r.argsort(): [5 3 7 1 2 8 4 0 6]
np.argsort(-r) [6 0 4 8 2 1 7 3 5]
升序排序
np.sort(r): [-2.3015387  -1.07296862 -0.7612069  -0.61175641 -0.52817175  0.3190391
  0.86540763  1.62434536  1.74481176]
降序排序
np.sort(-r): [-1.74481176 -1.62434536 -0.86540763 -0.3190391   0.52817175  0.61175641
  0.7612069   1.07296862  2.3015387 ]


In [49]:
s=np.random.randn(9)
print('s',s)
s.sort()
s #直接作用在原始数据上

s [-0.24937038  1.46210794 -2.06014071 -0.3224172  -0.38405435  1.13376944
 -1.09989127 -0.17242821 -0.87785842]


array([-2.06014071, -1.09989127, -0.87785842, -0.38405435, -0.3224172 ,
       -0.24937038, -0.17242821,  1.13376944,  1.46210794])

- ### ***二维数组***

In [50]:
np.random.seed(1)
t=np.random.randint(10,100,(3,3))
print('t.ndim',t.ndim)
print(t)
# 按行排序  axis=1 axis=-1 效果相同 行排序
print('t.argsort(axis=1)',t.argsort(axis=1))
print('t.argsort(axis=-1)',t.argsort(axis=-1))

# 按列排序
print('t.argsort(axis=0)',t.argsort(axis=0))

# 升序排序 
print('升序排序：',np.sort(t))

#降序排序
print('降序排序：',np.sort(-t))

t.ndim 2
[[47 22 82]
 [19 85 15]
 [89 74 26]]
t.argsort(axis=1) [[1 0 2]
 [2 0 1]
 [2 1 0]]
t.argsort(axis=-1) [[1 0 2]
 [2 0 1]
 [2 1 0]]
t.argsort(axis=0) [[1 0 1]
 [0 2 2]
 [2 1 0]]
升序排序： [[22 47 82]
 [15 19 85]
 [26 74 89]]
降序排序： [[-82 -47 -22]
 [-85 -19 -15]
 [-89 -74 -26]]


In [51]:
np.random.seed(1)
t1=np.random.randint(0,20,(3,3))
print(t1)
# sorted 默认的是升序  
# x[1]指定针对第1行内的元素进行升序
# 但相对应的元素也会随着第一行的变化发生相应的变化
sorted(t1,key=lambda x:x[1])

[[ 5 11 12]
 [ 8  9 11]
 [ 5 15  0]]


[array([ 8,  9, 11]), array([ 5, 11, 12]), array([ 5, 15,  0])]

In [52]:
'''sorted查看帮助'''
# 查看帮助
help(sorted)
sorted?
# 查看sorted的基本信息
np.info(sorted)
# 查看函数所有属性
dir(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.

Return a new list containing all items from the iterable in ascending order.

A custom key function can be supplied to customize the sort order, and the
reverse flag can be set to request the result in descending order.


['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

Signature: sorted(iterable, /, *, key=None, reverse=False)
Docstring:
Return a new list containing all items from the iterable in ascending order.

A custom key function can be supplied to customize the sort order, and the
reverse flag can be set to request the result in descending order.
Type:      builtin_function_or_method


# 三、数组的重塑

- np.reshape()

In [53]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [54]:
u=np.arange(24).reshape(2,3,4)
u.shape
# 两组 每组3行 每行4个  组 行 列

(2, 3, 4)

In [55]:
print('维度',u.ndim)
u

维度 3


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

- -1 表示缺失 
- resahpe(-1,1) #列
- reshape(1,-1) #行

In [56]:
np.arange(6).reshape(-1,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [57]:
k=np.arange(6)
print('k',k)
k1=k.reshape(1,-1)  #重塑成一行
print('k1',k1)

k [0 1 2 3 4 5]
k1 [[0 1 2 3 4 5]]


- ### ***np.ravel()***

In [58]:
np.ravel(u)
# 直接作用在变量 for example p.ravel()
np.random.seed(1)
p=np.random.randint(0,20,(2,3,4))
p1=np.ravel(p)
print('p1',p1)
print('p',p)
p2=p.ravel() #将数组变成扁平的数组
print('p2',p2)
print('p',p)

p1 [ 5 11 12  8  9 11  5 15  0 16  1 12  7 13  6 18  5 18 11 10 14 18  4  9]
p [[[ 5 11 12  8]
  [ 9 11  5 15]
  [ 0 16  1 12]]

 [[ 7 13  6 18]
  [ 5 18 11 10]
  [14 18  4  9]]]
p2 [ 5 11 12  8  9 11  5 15  0 16  1 12  7 13  6 18  5 18 11 10 14 18  4  9]
p [[[ 5 11 12  8]
  [ 9 11  5 15]
  [ 0 16  1 12]]

 [[ 7 13  6 18]
  [ 5 18 11 10]
  [14 18  4  9]]]


- **np.ravel(order='F')**

In [59]:
q=np.array([[1,2,3,4],[5,6,7,8,]])
print('按行压平')
print('np.ravel(q)',np.ravel(q))
print('q.ravel()',q.ravel())
print('按列压平')
print('q.ravel(order=F)',q.ravel(order='F'))

按行压平
np.ravel(q) [1 2 3 4 5 6 7 8]
q.ravel() [1 2 3 4 5 6 7 8]
按列压平
q.ravel(order=F) [1 5 2 6 3 7 4 8]


In [60]:
v=np.array([[1,2,3],[4,5,6]])
#将一个数组变成一个扁平数组。
print('默认按行进行压平')  
# 即下一行紧随上一行后面
v_ravel=v.ravel()
print(v_ravel)
print('order=F 认为按列压平:')
v_ra_f=v.ravel(order='F')
print(v_ra_f)

默认按行进行压平
[1 2 3 4 5 6]
order=F 认为按列压平:
[1 4 2 5 3 6]


# ** 扩充

- ### ***np.title(ndarray,(x,y))***
    - x 数组重复的次数
    - y 数组中的每个元素重复的次数
- ###  ***np.meshgrid(nd1,nd2)***
     - 依据数组自身进行扩充  nd1重复nd2的个数但是向下重复，nd2重复nd1的个数但是向右重复
- 两者的对比
     - 同：
         - 数组重复次数  数组的每个元素重复次数
         - 整个数组对针对设定的进行扩充
     - 异：     
        - 前者 对数组进行指定的重复次数和每个元素的重复次数
        - 后者 根据所给的数组确定了数组重复次数和数组每个元素重复的次数
        - 后者的每个数组只能占其中一个，如两个数组时，第一个只能数组重复且次数为第二个数组长度；第二个数组只能将每个元素进行重复且次数为第一个数组的长度

In [61]:
np.tile(np.array([[1,2,3],[4,5,6]]),(1,4))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6]])

In [62]:
rows,columns=np.meshgrid([2,3],[4,5,6])

In [63]:
rows_,columns_=(rows.tolist(),columns.tolist())

In [64]:
print(rows_,columns_,sep='\n')
# nd1重复了len(nd2)次 nd2的每个元素重复了len(nd1)次

[[2, 3], [2, 3], [2, 3]]
[[4, 4], [5, 5], [6, 6]]


# 四、素组的索引和切片 ***

- 普通的索引、切片 如似列表的索引切片

In [65]:
x=np.arange(100).reshape(5,5,4)
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]],

       [[60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]],

       [[80, 81, 82, 83],
        [84, 85, 86, 87],
        [88, 89, 90, 91],
        [92, 93, 94, 95],
        [96, 97, 98, 99]]])

In [66]:
x[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [67]:
# 按行索引的
x[0][0]

array([0, 1, 2, 3])

In [68]:
# 0组的除去最后一行的剩余所有
x[0][:-1]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
# 0组的最后一行
x[0][-1]

array([16, 17, 18, 19])

In [70]:
x[:2]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]]])

 - ### ***数组特有的索引切片***

- ndarray[行,列]
  - ndarray[:,:] #索出所有行所有列
  - ndarray[[,],[,]] #索出指定的多行（可连续(:)亦可不连续(,)）
- : 连续索引 切记不需要加[]
- [,] 挑选索引  切记需要用列表盛装

选择索引

In [71]:
# 表示索取0组和1组
x[[0,1]]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]]])

In [72]:
x[[0,1],[0,1]]
# 索引出的是0组的行1和1组的行1  0,0 1,1

array([[ 0,  1,  2,  3],
       [24, 25, 26, 27]])

连续索引

In [73]:
x[:2]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]]])

In [74]:
x[0:2,0:2]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27]]])

混合索引 选择 连续

In [75]:
x[[0,1],0:2]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27]]])

In [76]:
x[:2,[0,1]]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27]]])

嵌套索引
- 多层索引 
    - 先索引出组
    - 再索引出组中的具体元素

In [77]:
x[[0,1]][:,[1,3]]  #索引出0组和1组 的所有行但只是1、3的所有行据

array([[[ 4,  5,  6,  7],
        [12, 13, 14, 15]],

       [[24, 25, 26, 27],
        [32, 33, 34, 35]]])

In [78]:
x[:2][1]
# 1组

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [79]:
x[:2][:,1]
# 0组的行1

array([[ 4,  5,  6,  7],
       [24, 25, 26, 27]])

In [80]:
x[:2][:,1:3]

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]]])

- ：索引出所有的  存在则代表所有组是对索引出组意愿的加深

In [81]:
x[:2][:2,1]
# 索引出0组1组的行1

array([[ 4,  5,  6,  7],
       [24, 25, 26, 27]])

In [82]:
x[:2][:2,:2]
# 索引出0组1组的行1和行2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27]]])

- ## **索引时的原则是由外到内层层索引的**

 - 小拓展

In [83]:
rows,columns=np.meshgrid([1,2],[3,4,5])

In [84]:
rows

array([[1, 2],
       [1, 2],
       [1, 2]])

In [85]:
columns

array([[3, 3],
       [4, 4],
       [5, 5]])

# 五、二维数组的合并  np.concatenate

## 1.纵向合并

- 合并原则
    - 两者的形状必须相同 维度也要相同

In [86]:
a1=np.random.normal(2,4,(2,3))
a2=np.random.rand(2,3)

In [87]:
a1

array([[4.70893602, 1.5724863 , 4.90109626],
       [5.73955662, 6.47318791, 2.22245276]])

In [88]:
a2

array([[0.82914691, 0.82960336, 0.27304997],
       [0.0592432 , 0.67052804, 0.59306552]])

- 纵向合并

In [89]:
np.concatenate((a1,a2),axis=0)

array([[4.70893602, 1.5724863 , 4.90109626],
       [5.73955662, 6.47318791, 2.22245276],
       [0.82914691, 0.82960336, 0.27304997],
       [0.0592432 , 0.67052804, 0.59306552]])

## 2.横向合并

In [90]:
np.concatenate((a1,a2),axis=1)

array([[4.70893602, 1.5724863 , 4.90109626, 0.82914691, 0.82960336,
        0.27304997],
       [5.73955662, 6.47318791, 2.22245276, 0.0592432 , 0.67052804,
        0.59306552]])

# 六、数组的运算

In [91]:
b1=np.random.randint(0,10,(2,3))
b2=np.random.randint(0,10,(2,3))

In [92]:
print('b1',b1,'b2',b2,sep='\n')

b1
[[6 5 1]
 [9 3 4]]
b2
[[8 1 4]
 [0 3 9]]


In [93]:
# +
b1+b2
# 对应位置上的元素相加

array([[14,  6,  5],
       [ 9,  6, 13]])

In [94]:
# -
b1-b2

array([[-2,  4, -3],
       [ 9,  0, -5]])

In [95]:
#  *
b1*b2
# 对应位置元素相乘

array([[48,  5,  4],
       [ 0,  9, 36]])

In [96]:
#  /
b1/b2
# 对应位置元素进行相除

E:\python\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([[0.75      , 5.        , 0.25      ],
       [       inf, 1.        , 0.44444444]])

# 七、广播运算
- 当两个数组的形状不相同时，可以通过扩展数组的方式来实现加减乘除的运算
- 应用场景
    - 两个数组的维数不相等，但后缘维度轴长相符
    - 有一方的长度为1 

- ***1、后缘维度轴长相等***

- 二维与一维相加

In [97]:
c1=np.array([[0,0,0],[1,1,1],[2,2,2],[3,3,3]])
c2=np.array([1,2,3]).reshape(-1,1)
c3=np.array([1,2,3])

In [98]:
print('c1.shape',c1.shape)
print('c2.shape',c2.shape)
print('c3.shape',c3.shape)

c1.shape (4, 3)
c2.shape (3, 1)
c3.shape (3,)


In [99]:
# c1+c2
# 报错的原因是c2是列向量且长度与c1的列的长度不同，无法进行广播

In [100]:
# 一维数组c3在轴0上向下广播即向下扩充
c1+c3
# 3即为两个数组的后缘维度长度

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

- 三维与二维相加

In [101]:
c4=np.arange(20).reshape(2,2,5)
c5=np.arange(10).reshape(2,5) #将c5扩成与c4一样的维度
# （2,5）即为两个数组的后缘维度轴长

In [102]:
print('c4',c4)
print('c5',c5)
print('c4.ndim',c4.ndim)
print('c5.ndim',c5.ndim)

c4 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
c5 [[0 1 2 3 4]
 [5 6 7 8 9]]
c4.ndim 3
c5.ndim 2


In [103]:
c4+c5
# 二维数组在轴0上广播

array([[[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18]],

       [[10, 12, 14, 16, 18],
        [20, 22, 24, 26, 28]]])

- ***2、某个维度轴长为1***

二维上轴1的长度为1

In [104]:
d1=np.arange(12).reshape(3,4)
d2=np.arange(3).reshape(3,1)
# d2在轴1上的维度是1，则可以在1轴上进行广播

In [105]:
d1+d2

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

三维情况

In [106]:
e1=np.arange(12).reshape(1,3,4)
# e1会沿着1轴方向进行广播
e2=np.arange(24).reshape(2,3,4)

In [107]:
e1+e2

array([[[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]],

       [[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]]])

三维与二维

In [108]:
f1=np.arange(24).reshape(2,3,4)
f2=np.arange(4).reshape(1,4)
# f2会扩充成（2,3,4）

In [109]:
print('f1',f1)
print('f2',f2)

f1 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
f2 [[0 1 2 3]]


In [110]:
f1+f2

array([[[ 0,  2,  4,  6],
        [ 4,  6,  8, 10],
        [ 8, 10, 12, 14]],

       [[12, 14, 16, 18],
        [16, 18, 20, 22],
        [20, 22, 24, 26]]])

总之当一方与另一方有不足之处，不足方会尽量扩充成与之大小相同一样的，但需要满足广播的两个要求之一

# 八、通用函数 ：元素对元素的函数

- 一元通用函数 只需一个变量
    - np.abs np.sqrt np.square等
- 二元通用函数  需要两个变量
    - np.add np.maximun np.minimun np.multiply等

In [111]:
np.abs(np.array([-1,-9,3]))

array([1, 9, 3])

In [112]:
np.sqrt(np.array([9,16,25]))

array([3., 4., 5.])

In [113]:
np.square(np.array([3,4,5]))

array([ 9, 16, 25], dtype=int32)

In [114]:
# 二元通用函数
g1=np.arange(12)
g2=np.arange(10,22)

In [115]:
print('g1',g1)
print('g2',g2)

g1 [ 0  1  2  3  4  5  6  7  8  9 10 11]
g2 [10 11 12 13 14 15 16 17 18 19 20 21]


In [116]:
print('np.add(g1,100)',np.add(g1,100))
print('g1+100=',g1+100)

np.add(g1,100) [100 101 102 103 104 105 106 107 108 109 110 111]
g1+100= [100 101 102 103 104 105 106 107 108 109 110 111]


In [117]:
print('np.add(g1,g2)',np.add(g1,g2))
print('g1+g2=',g1+g2)

np.add(g1,g2) [10 12 14 16 18 20 22 24 26 28 30 32]
g1+g2= [10 12 14 16 18 20 22 24 26 28 30 32]


- np.minimum()  数据的形状要相同
- np.maximum()

In [118]:
# np.minimum?
np.minimum([1,3,9],[0,4,7])
# 对应位置的元素进行对比返回值小的元素

array([0, 3, 7])

In [119]:
np.minimum([1,3,4],9)

array([1, 3, 4])

In [120]:
np.maximum([1,3,9],[0,4,7])

array([1, 4, 9])

In [121]:
np.maximum([1,3,4],[9,10,2])

array([ 9, 10,  4])

- np.multiply(x,y)  两个变量相乘 等同于x*y

In [122]:
print('np.multiply',np.multiply(g1,g2))
print('g1*g2',g1*g2)

np.multiply [  0  11  24  39  56  75  96 119 144 171 200 231]
g1*g2 [  0  11  24  39  56  75  96 119 144 171 200 231]


# 九、数组常用的方法

- ***T方法***

In [123]:
h1=np.array([1,2,3,4]).T
h1
# 一维数组转置后还是自身

array([1, 2, 3, 4])

In [124]:
h2=np.array([[1,2,3],[4,5,6]])
print('h2',h2)
print('h2.T',h2.T)

h2 [[1 2 3]
 [4 5 6]]
h2.T [[1 4]
 [2 5]
 [3 6]]


- **transepose方法** ***转置***
    - 转换形状

In [125]:
# help(transepose)
# transepose?
np.info(np.transpose)

 transpose(a, axes=None)

Permute the dimensions of an array.

Parameters
----------
a : array_like
    Input array.
axes : list of ints, optional
    By default, reverse the dimensions, otherwise permute the axes
    according to the values given.

Returns
-------
p : ndarray
    `a` with its axes permuted.  A view is returned whenever
    possible.

See Also
--------
moveaxis
argsort

Notes
-----
Use `transpose(a, argsort(axes))` to invert the transposition of tensors
when using the `axes` keyword argument.

Transposing a 1-D array returns an unchanged view of the original array.

Examples
--------
>>> x = np.arange(4).reshape((2,2))
>>> x
array([[0, 1],
       [2, 3]])

>>> np.transpose(x)
array([[0, 2],
       [1, 3]])

>>> x = np.ones((1, 2, 3))
>>> np.transpose(x, (1, 0, 2)).shape
(2, 1, 3)


In [126]:
k1=np.arange(12).reshape(3,4)
print('k1',k1)
print('k1.transpose(0,1)',k1.transpose(0,1)) # =k1
# T
print('np.transpose',np.transpose(k1)) # k1.T
print('k1.transpose(1,0)',k1.transpose(1,0)) # =k1.T

k1 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
k1.transpose(0,1) [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
np.transpose [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
k1.transpose(1,0) [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


- astype方法 转化类型
- dtype 数组类型
- type 查类型的函数

In [127]:
k3=np.random.randint(1,10,(3,3))
k3.dtype

dtype('int32')

In [128]:
k3.astype(float)

array([[3., 1., 5.],
       [3., 8., 8.],
       [9., 7., 4.]])

In [129]:
type(k3.astype(float))

numpy.ndarray

In [130]:
k3.astype(str)

array([['3', '1', '5'],
       ['3', '8', '8'],
       ['9', '7', '4']], dtype='<U11')

- ### **tolist 方法 将数组转化成列表**

In [131]:
k4=np.array([[1,2,3],[4,5,6]])
k4

array([[1, 2, 3],
       [4, 5, 6]])

In [132]:
k4.tolist()

[[1, 2, 3], [4, 5, 6]]

In [133]:
k5=np.array([1,2,3,np.nan])
k5.tolist()

[1.0, 2.0, 3.0, nan]

# 十、np.char模块下的字符串函数

- np.char.add() np.char.upper() np.char.split() 等字符串的大多函数此处都能用

In [134]:
l3=np.array([1,2,3])
l4=l3.astype(str)
print(l4)
np.char.add(l4,'b')
# 字符串的添加

['1' '2' '3']


array(['1b', '2b', '3b'], dtype='<U12')

In [135]:
l5=np.array(['a'])
l5

array(['a'], dtype='<U1')

In [136]:
np.char.add(l4,l5)

array(['1a', '2a', '3a'], dtype='<U12')

- np.char.upper() 

In [137]:
np.char.upper(l5)

array(['A'], dtype='<U1')

In [138]:
l6=np.array(['a;b;c','d;e;f'])
l6

array(['a;b;c', 'd;e;f'], dtype='<U5')

In [139]:
result=np.char.split(l6,sep=';')
print('result',result)
print(result.tolist())

result [list(['a', 'b', 'c']) list(['d', 'e', 'f'])]
[['a', 'b', 'c'], ['d', 'e', 'f']]


# 十一、矩阵运算

## 1、数组点积 np.dot(,) ：矩阵乘法 结果是一个数值

- 一维数组

In [140]:
np.random.seed(2)
m1=np.random.randint(1,5,6)
m2=np.random.randint(1,5,6)

np.dot(m1,m2)
print('np.dot(m1,m2):',np.dot(m1,m2))

m1.dot(m2)
print('m1.dot(m2):',m1.dot(m2))

m1 @ m2
print('m1 @ m2:',m1 @ m2)

np.multiply(m1,m2)
print('np.multiply(m1,m2):',np.matmul(m1,m2))

np.vdot(m1,m2)
print('np.vdot(m1,m2):',np.vdot(m1,m2))

np.dot(m1,m2): 42
m1.dot(m2): 42
m1 @ m2: 42
np.multiply(m1,m2): 42
np.vdot(m1,m2): 42


- 二维数组
    - 要注意满足前者的列数等于后者行数

In [141]:
np.random.seed(10)
m3=np.random.randint(1,9,(3,4))
np.random.seed(12)
m4=np.random.randint(1,9,(4,3))

In [142]:
print('m3',m3)
print('m4',m4)

m3 [[2 6 5 8]
 [1 2 4 5]
 [2 6 1 6]]
m4 [[4 4 7]
 [6 2 3]
 [4 4 5]
 [1 7 2]]


In [143]:
print('np.dot(m3,m4):',np.dot(m3,m4))
print('m3.dot(m4):',m3.dot(m4))
print('m3 @ m4:',m3 @ m4)
print('np.matmul(m3,m4)',np.matmul(m3,m4))
print('np.vdot(m3,m4)',np.vdot(m3,m4))

np.dot(m3,m4): [[72 96 73]
 [37 59 43]
 [54 66 49]]
m3.dot(m4): [[72 96 73]
 [37 59 43]
 [54 66 49]]
m3 @ m4: [[72 96 73]
 [37 59 43]
 [54 66 49]]
np.matmul(m3,m4) [[72 96 73]
 [37 59 43]
 [54 66 49]]
np.vdot(m3,m4) 194


## 2、数组内积 叉乘积 np.inner(,)
##### 二维数组相当于矩阵，那么矩阵的内积就等于一个矩阵乘于另一个矩阵的转置

- 一维数组

In [144]:
np.random.seed(13)
m5=np.arange(8)
np.random.seed(14)
m6=np.arange(8)

In [145]:
np.inner(m5,m6)

140

- 二维数组

In [146]:
np.random.seed(14)
m7=np.random.randint(1,5,(3,4))
np.random.seed(15)
m8=np.random.randint(1,5,(3,4))

In [147]:
np.inner(m7,m8)

array([[13, 30, 31],
       [17, 33, 39],
       [12, 16, 24]])

## 矩阵运算的总结
- 一维数组情况下  
    - 点积与内积的结果一样，均为一个数值
- 二维数组情况下  
    - 点积：矩阵的乘法 如1,1位置的结果为数组1的第一行对应位置上的元素乘于数组2的第一列对应位置上的元素再加总得到的总结果 
    - 内积： 数组1乘于数组2的转，每个位置的结果数组1的行乘于数组列对应位置的元素相加总的最终结果
    - 点积对于数组的要求：一个数组的列数要等于另一个数组的行数
    - 内积对于数组的要求：两个数组的形状要相同即两个数组的行数、列数要一致

In [148]:
# 一维数组
np.random.seed(121)
n1=np.random.randint(1,9,5)
np.random.randint(11)
n2=np.random.randint(1,9,5)
print('dot:')
print(np.dot(n1,n2))
print('inner:')
np.inner(n1,n2)

dot:
90
inner:


90

In [149]:
# 二维数组
np.random.seed(121)
n3=np.random.randint(1,9,(3,4))
np.random.seed(11)
n4=np.random.randint(1,9,(4,3))
n5=np.random.randint(1,9,(3,4))

In [150]:
print('n3:',n3)
print('n4:',n4)
print('n5:',n5)

n3: [[3 6 1 8]
 [5 2 5 4]
 [8 1 7 3]]
n4: [[2 8 1]
 [4 2 8]
 [6 5 2]
 [8 3 1]]
n5: [[6 5 1 6]
 [1 6 5 6]
 [5 3 5 2]]


In [151]:
# dot
n3 @ n4

array([[100,  65,  61],
       [ 80,  81,  35],
       [ 86, 110,  33]])

In [152]:
# inner
np.inner(n3,n5)

array([[97, 92, 54],
       [69, 66, 64],
       [78, 67, 84]])

## 3、矩阵行列式 np.linalg.inv()
### 必须是方阵才可以求行列式

In [153]:
b8=np.random.randint(1,20,(4,4))
b8

array([[11,  6,  8, 18],
       [18,  4,  7, 12],
       [19, 19,  1, 16],
       [ 1,  7, 12, 11]])

In [154]:
np.linalg.det(b8)

-25839.000000000004

## 4、矩阵的逆矩阵 np.linalg.inv()  
### 必须是方阵才可以求逆

In [155]:
b9=np.random.randint(1,20,(4,4))
b9

array([[13, 15,  8, 16],
       [ 1,  9, 17,  6],
       [ 8, 19,  4,  2],
       [17,  4,  9, 18]])

In [156]:
np.linalg.inv(b9)

array([[-0.1444452 , -0.02094489,  0.09774283,  0.12451705],
       [ 0.06073341, -0.00386362,  0.01803023, -0.05470074],
       [-0.08140717,  0.06656273,  0.02270725,  0.04765133],
       [ 0.16362774, -0.0126415 , -0.10767302, -0.07371382]])

# 十二、 特殊元素构成数组

- 数组里面的基本元素类型：数值，字符串，布尔对象
- 还可以是字典、集合等对象

In [157]:
np.array({2,4,6,7,8,9})

array({2, 4, 6, 7, 8, 9}, dtype=object)

In [158]:
np.array({'a':1,'b':4})

array({'a': 1, 'b': 4}, dtype=object)

## 十三、二维数组的协方差矩阵、相关矩阵

In [159]:
np.random.seed(3)
data=np.random.rand(5,6)

In [160]:
data

array([[0.5507979 , 0.70814782, 0.29090474, 0.51082761, 0.89294695,
        0.89629309],
       [0.12558531, 0.20724288, 0.0514672 , 0.44080984, 0.02987621,
        0.45683322],
       [0.64914405, 0.27848728, 0.6762549 , 0.59086282, 0.02398188,
        0.55885409],
       [0.25925245, 0.4151012 , 0.28352508, 0.69313792, 0.44045372,
        0.15686774],
       [0.54464902, 0.78031476, 0.30636353, 0.22195788, 0.38797126,
        0.93638365]])

In [161]:
np.cov(data)

array([[ 0.05616121,  0.01009702, -0.04132441, -0.00709003,  0.04036883],
       [ 0.01009702,  0.03569261,  0.01664814,  0.00639473,  0.01766799],
       [-0.04132441,  0.01664814,  0.0664892 , -0.01148374, -0.00584631],
       [-0.00709003,  0.00639473, -0.01148374,  0.03529008, -0.03342855],
       [ 0.04036883,  0.01766799, -0.00584631, -0.03342855,  0.07861884]])

- 相关矩阵  常用作查看自变量间的相关性程度

In [162]:
np.corrcoef(data)

array([[ 1.        ,  0.2255204 , -0.67625879, -0.1592589 ,  0.6075256 ],
       [ 0.2255204 ,  1.        ,  0.3417441 ,  0.18018011,  0.33352982],
       [-0.67625879,  0.3417441 ,  1.        , -0.23707272, -0.08086179],
       [-0.1592589 ,  0.18018011, -0.23707272,  1.        , -0.63464071],
       [ 0.6075256 ,  0.33352982, -0.08086179, -0.63464071,  1.        ]])

## 十四、nump其他常用函数

- np.mean()
- np.sum(,keepdims=) keepdims=True表示保持原有的维度
- np.argmax()
- np.argmin()

In [163]:
np.random.seed(2)
O1=np.random.randint(0,20,(3,3))
O1

array([[ 8, 15, 13],
       [ 8, 11, 18],
       [11,  8,  7]])

In [164]:
O1.mean()

11.0

In [165]:
np.sum(O1)

99

In [166]:
np.sum(O1,keepdims=True)

array([[99]])

In [167]:
np.sum(O1,axis=0,keepdims=True)

array([[27, 34, 38]])

In [168]:
np.sum(O1,axis=1,keepdims=False)

array([36, 37, 26])

In [169]:
# 返回最大值的索引号
np.argmax(O1)

5

In [170]:
# 返回最小值的索引号
np.argmin(O1)

8

In [171]:
# 返回最小值
np.min(O1)

7

In [172]:
# 返回最大值
np.max(O1)

18